//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.DBContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AVSTechnoEntities : DbContext
    {
        public AVSTechnoEntities()
            : base("name=AVSTechnoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TS_CustomerProductTransaction> TS_CustomerProductTransaction { get; set; }
        public virtual DbSet<TS_Customers> TS_Customers { get; set; }
        public virtual DbSet<TS_ModelSerialNos> TS_ModelSerialNos { get; set; }
        public virtual DbSet<TS_PaymentModes> TS_PaymentModes { get; set; }
        public virtual DbSet<TS_PaymentTypes> TS_PaymentTypes { get; set; }
        public virtual DbSet<TS_ProductModels> TS_ProductModels { get; set; }
        public virtual DbSet<TS_ProductTypes> TS_ProductTypes { get; set; }
        public virtual DbSet<TS_Roles> TS_Roles { get; set; }
        public virtual DbSet<TS_Users> TS_Users { get; set; }
        public virtual DbSet<TS_Vendors> TS_Vendors { get; set; }
        public virtual DbSet<TS_Model_SerialNos> TS_Model_SerialNos { get; set; }
        public virtual DbSet<TS_Models> TS_Models { get; set; }
        public virtual DbSet<TS_CustomerProducts> TS_CustomerProducts { get; set; }
        public virtual DbSet<TS_Materials> TS_Materials { get; set; }
    
        public virtual ObjectResult<usp_ProductSalePurChaseReport_Result> usp_ProductSalePurChaseReport(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ProductSalePurChaseReport_Result>("usp_ProductSalePurChaseReport", fromDateParameter, toDateParameter);
        }
    }
}
