//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_Customers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TS_Customers()
        {
            this.TS_CustomerProducts = new HashSet<TS_CustomerProducts>();
        }
    
        public int CId { get; set; }
        public string CName { get; set; }
        public string CZipCode { get; set; }
        public string CPhoneNumber { get; set; }
        public string CEmail { get; set; }
        public string CAddress { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public string CGSTIN { get; set; }
        public string CStateCode { get; set; }
        public string SName { get; set; }
        public string SAddress { get; set; }
        public string SPhoneNumber { get; set; }
        public string SGSTIN { get; set; }
        public string SStateCode { get; set; }
        public string CState { get; set; }
        public string SState { get; set; }
        public string SEmail { get; set; }
        public Nullable<bool> IsSameAs { get; set; }
    
        public virtual TS_Users TS_Users { get; set; }
        public virtual TS_Users TS_Users1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TS_CustomerProducts> TS_CustomerProducts { get; set; }
    }
}
