//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_CustomerProducts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TS_CustomerProducts()
        {
            this.TS_CustomerProductTransaction = new HashSet<TS_CustomerProductTransaction>();
        }
    
        public int CProductID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> CGST { get; set; }
        public Nullable<decimal> SGST { get; set; }
        public Nullable<decimal> IGST { get; set; }
        public Nullable<decimal> SellPrice { get; set; }
        public Nullable<decimal> NetTotal { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> GrossTotal { get; set; }
        public Nullable<int> PaymentTypeId { get; set; }
        public Nullable<int> PaymentModeId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public string SerialNo { get; set; }
        public string ACSerialNo { get; set; }
        public Nullable<int> ProductModelId { get; set; }
        public Nullable<decimal> PendingAmount { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
    
        public virtual TS_Users TS_Users { get; set; }
        public virtual TS_Customers TS_Customers { get; set; }
        public virtual TS_PaymentModes TS_PaymentModes { get; set; }
        public virtual TS_PaymentTypes TS_PaymentTypes { get; set; }
        public virtual TS_Models TS_Models { get; set; }
        public virtual TS_Users TS_Users1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TS_CustomerProductTransaction> TS_CustomerProductTransaction { get; set; }
    }
}
