//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_CustomerProductTransaction
    {
        public int CPTransactionID { get; set; }
        public Nullable<int> CProductID { get; set; }
        public Nullable<decimal> NewPayment { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public Nullable<decimal> RemainingAmount { get; set; }
        public Nullable<int> PaymentTypeId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual TS_Users TS_Users { get; set; }
        public virtual TS_PaymentTypes TS_PaymentTypes { get; set; }
        public virtual TS_Users TS_Users1 { get; set; }
        public virtual TS_CustomerProducts TS_CustomerProducts { get; set; }
    }
}
