//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_Models
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TS_Models()
        {
            this.TS_Model_SerialNos = new HashSet<TS_Model_SerialNos>();
            this.TS_CustomerProducts = new HashSet<TS_CustomerProducts>();
            this.TS_ProductModels = new HashSet<TS_ProductModels>();
        }
    
        public int ProductModelId { get; set; }
        public Nullable<int> ProductTypeId { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<int> TotalUnits { get; set; }
        public Nullable<decimal> CGST { get; set; }
        public Nullable<decimal> SGST { get; set; }
        public Nullable<decimal> IGST { get; set; }
        public Nullable<decimal> TotalTax { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public string ModelName { get; set; }
        public Nullable<bool> IsIGST { get; set; }
        public Nullable<decimal> TaxPercent { get; set; }
        public string HSNCode { get; set; }
        public string SerialNo { get; set; }
        public string ACSerialNo { get; set; }
        public string Capacity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TS_Model_SerialNos> TS_Model_SerialNos { get; set; }
        public virtual TS_Users TS_Users { get; set; }
        public virtual TS_ProductTypes TS_ProductTypes { get; set; }
        public virtual TS_Users TS_Users1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TS_CustomerProducts> TS_CustomerProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TS_ProductModels> TS_ProductModels { get; set; }
    }
}
