//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_ProductModels
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TS_ProductModels()
        {
            this.TS_ModelSerialNos = new HashSet<TS_ModelSerialNos>();
        }
    
        public int ModelID { get; set; }
        public Nullable<int> ProductTypeId { get; set; }
        public Nullable<int> MaterialID { get; set; }
        public string MName { get; set; }
        public string MDescription { get; set; }
        public string Mcapacity { get; set; }
        public Nullable<int> MQty { get; set; }
        public Nullable<decimal> MUnitPrice { get; set; }
        public Nullable<decimal> MCGST { get; set; }
        public Nullable<decimal> MSGST { get; set; }
        public Nullable<decimal> MIGST { get; set; }
        public Nullable<decimal> MTotalPrice { get; set; }
        public Nullable<decimal> MTaxTotal { get; set; }
        public Nullable<decimal> MGrossAmount { get; set; }
        public string MSrCode { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<int> ProductModelId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TS_ModelSerialNos> TS_ModelSerialNos { get; set; }
        public virtual TS_Users TS_Users { get; set; }
        public virtual TS_ProductTypes TS_ProductTypes { get; set; }
        public virtual TS_Users TS_Users1 { get; set; }
        public virtual TS_Models TS_Models { get; set; }
        public virtual TS_Materials TS_Materials { get; set; }
    }
}
