//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TS_Users()
        {
            this.TS_CustomerProductTransaction = new HashSet<TS_CustomerProductTransaction>();
            this.TS_CustomerProductTransaction1 = new HashSet<TS_CustomerProductTransaction>();
            this.TS_Customers = new HashSet<TS_Customers>();
            this.TS_Customers1 = new HashSet<TS_Customers>();
            this.TS_ModelSerialNos = new HashSet<TS_ModelSerialNos>();
            this.TS_ModelSerialNos1 = new HashSet<TS_ModelSerialNos>();
            this.TS_PaymentModes = new HashSet<TS_PaymentModes>();
            this.TS_PaymentModes1 = new HashSet<TS_PaymentModes>();
            this.TS_PaymentTypes = new HashSet<TS_PaymentTypes>();
            this.TS_PaymentTypes1 = new HashSet<TS_PaymentTypes>();
            this.TS_ProductModels = new HashSet<TS_ProductModels>();
            this.TS_ProductModels1 = new HashSet<TS_ProductModels>();
            this.TS_ProductTypes = new HashSet<TS_ProductTypes>();
            this.TS_ProductTypes1 = new HashSet<TS_ProductTypes>();
            this.TS_Vendors = new HashSet<TS_Vendors>();
            this.TS_Vendors1 = new HashSet<TS_Vendors>();
            this.TS_Model_SerialNos = new HashSet<TS_Model_SerialNos>();
            this.TS_Model_SerialNos1 = new HashSet<TS_Model_SerialNos>();
            this.TS_Models = new HashSet<TS_Models>();
            this.TS_Models1 = new HashSet<TS_Models>();
            this.TS_CustomerProducts = new HashSet<TS_CustomerProducts>();
            this.TS_CustomerProducts1 = new HashSet<TS_CustomerProducts>();
            this.TS_Materials = new HashSet<TS_Materials>();
            this.TS_Materials1 = new HashSet<TS_Materials>();
        }
    
        public int UserID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TS_CustomerProductTransaction> TS_CustomerProductTransaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TS_CustomerProductTransaction> TS_CustomerProductTransaction1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TS_Customers> TS_Customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TS_Customers> TS_Customers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TS_ModelSerialNos> TS_ModelSerialNos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TS_ModelSerialNos> TS_ModelSerialNos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TS_PaymentModes> TS_PaymentModes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TS_PaymentModes> TS_PaymentModes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TS_PaymentTypes> TS_PaymentTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TS_PaymentTypes> TS_PaymentTypes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TS_ProductModels> TS_ProductModels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TS_ProductModels> TS_ProductModels1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TS_ProductTypes> TS_ProductTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TS_ProductTypes> TS_ProductTypes1 { get; set; }
        public virtual TS_Roles TS_Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TS_Vendors> TS_Vendors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TS_Vendors> TS_Vendors1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TS_Model_SerialNos> TS_Model_SerialNos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TS_Model_SerialNos> TS_Model_SerialNos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TS_Models> TS_Models { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TS_Models> TS_Models1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TS_CustomerProducts> TS_CustomerProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TS_CustomerProducts> TS_CustomerProducts1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TS_Materials> TS_Materials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TS_Materials> TS_Materials1 { get; set; }
    }
}
