//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_Vendors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TS_Vendors()
        {
            this.TS_Materials = new HashSet<TS_Materials>();
        }
    
        public int VendorID { get; set; }
        public string VName { get; set; }
        public string VAddress { get; set; }
        public string VPhone { get; set; }
        public string VEmail { get; set; }
        public string VFax { get; set; }
        public string VGSTIN { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual TS_Users TS_Users { get; set; }
        public virtual TS_Users TS_Users1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TS_Materials> TS_Materials { get; set; }
    }
}
